#' @name synLFQ8
#'
#' @title Synthetic yearly length-frequency data VIII with seasonal oscillation
#'
#'
#' @description Synthetic length-frequency data as generated by the
#'     function \code{virtualPop2} from the \emph{fishdynr} package
#'     (Taylor and Mildenberger, 2018). Can be used by
#'     \code{\link[TropFishR]{ELEFAN}},
#'     \code{\link[TropFishR]{ELEFAN_SA}}, or
#'     \code{\link[TropFishR]{ELEFAN_GA}}.  The data is generated with
#'     the following von Bertalanffy growth parameters: \itemize{
#'     \item K = 0.5 +/- 0.15 (CV) \item Linf = 80 +/- 0.15 (CV) \item
#'     C = 0.4 \item ts = 0.5 \item t_anchor around 0.2 (Time when
#'     yearly recruitment pulse occurs; e.g. 0 = Jan 1, 0.25 = Apr 1,
#'     0.5 = Jul 1, 0.75 = Oct 1; repro_wt = c(1, 1, 1, 1, 1, 0, 0, 0,
#'     0, 0, 0, 0)) }
#'
#' Further settings include:
#' \itemize{
#'   \item Lmat.f = 40 (length at maturity)
#'   \item Lmat.m = 36 (length at maturity)
#'   \item L50 = 20 (length at 50\% prob. of capture via trawl net)
#'   \item wqs = 4 (width between 25\% and 75\% prob. of capture quantiles;
#'   i.e. wqs = 0 is knife-edge selection)
#'   \item M = 0.7 (Natural mortality rate)
#'   \item harvest_rate = 1, 0.8, 0.4, 0.1 for different years (Fishing mortality rate)
#' }
#'
#' @docType data
#'
#' @format A list of class lfq consisting of:
#' \itemize{
#'   \item \strong{dates} dates of sampling times (class Date),
#'   \item \strong{midLengths} midpoints of the length classes,
#'   \item \strong{catch} matrix with catches/counts per length class (row) and
#'      sampling date (column).
#' }
#'
#' @source Taylor, M & T. K. Mildenberger  (2018). fishdynr: Fisheries science related population dynamics
#' models. R package version 0.5. https://github.com/tokami/fishdynr
#'
#' @usage data(synLFQ8)
#' @keywords data dataset length-frequency
#'
#' @examples
#' data(synLFQ8)
#'
#' # plot of length frequencies
#' plot(synLFQ8, Fname = "catch")
#'
#' # plot of restructured length frequencies
#' synLFQ8 <- lfqRestructure(synLFQ8, MA = 11)
#' plot(synLFQ8, Fname = "rcounts")
#'
#'
#'
NULL
